(async function(){
'use strict';
const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const boot=qs('#boot'),graphStatus=qs('#graph-status'),canvas=qs('#universe-canvas'),labelLayer=qs('#label-layer');
const mobile=innerWidth<820,reduceMedia=matchMedia('(prefers-reduced-motion: reduce)');
let THREE;
try{THREE=await import('https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js')}catch(err){console.warn('3D layer unavailable',err);boot?.classList.add('done');if(graphStatus)graphStatus.textContent='Graph · semantic mode';return}

const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.3:1.75));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x090706,.021);
const camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,280);camera.position.set(0,2.4,19);
const C={amber:0xe3a35a,rust:0xc66743,cyan:0x7fcad2,green:0x85bd8b,ivory:0xf3eadc,blue:0x78a7ff,dim:0x826f59};
const root=new THREE.Group(),orbitalRoot=new THREE.Group(),nodeRoot=new THREE.Group(),graphRoot=new THREE.Group(),instrumentRoot=new THREE.Group();scene.add(root);root.add(orbitalRoot,nodeRoot,graphRoot,instrumentRoot);

function glowTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,247,229,1)');g.addColorStop(.13,'rgba(255,205,139,.95)');g.addColorStop(.42,'rgba(227,142,70,.28)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,128,128);return new THREE.CanvasTexture(c)}
const glowTex=glowTexture();
function sprite(color,size=.8,opacity=.85){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex,color,transparent:true,opacity,depthWrite:false}));s.scale.set(size,size,1);return s}

// ---------- Particle field + morph targets ----------
const starCount=mobile?1250:3200,starNow=new Float32Array(starCount*3),starColor=new Float32Array(starCount*3);const targets={};
function fillCosmos(arr){for(let i=0;i<starCount;i++){const r=18+Math.random()*80,t=Math.random()*Math.PI*2,u=Math.acos(2*Math.random()-1);arr[i*3]=Math.sin(u)*Math.cos(t)*r;arr[i*3+1]=Math.cos(u)*r*.58;arr[i*3+2]=Math.sin(u)*Math.sin(t)*r}}
function fillOrbit(arr){for(let i=0;i<starCount;i++){const ring=2.7+(i%13)*.48+Math.random()*.25,a=Math.random()*Math.PI*2;arr[i*3]=Math.cos(a)*ring;arr[i*3+1]=(Math.random()-.5)*.5;arr[i*3+2]=Math.sin(a)*ring*.68}}
function fillLattice(arr){const side=Math.ceil(Math.sqrt(starCount));for(let i=0;i<starCount;i++){const x=i%side,y=Math.floor(i/side);arr[i*3]=(x-side/2)*.29+(Math.random()-.5)*.08;arr[i*3+1]=(y-side/2)*.22+(Math.random()-.5)*.08;arr[i*3+2]=(Math.random()-.5)*5.2}}
function fillOptical(arr){const path=[[-12,-2,-5],[-8,-2,-4],[-4,-1.4,-3],[0,-1.8,-2],[4,-1,-1],[8,-1.6,0],[12,-1.2,1]];for(let i=0;i<starCount;i++){const seg=i%(path.length-1),f=Math.random(),a=path[seg],b=path[seg+1];arr[i*3]=a[0]+(b[0]-a[0])*f+(Math.random()-.5)*1.1;arr[i*3+1]=a[1]+(b[1]-a[1])*f+(Math.random()-.5)*1.25;arr[i*3+2]=a[2]+(b[2]-a[2])*f+(Math.random()-.5)*1.2}}
function fillTimeline(arr){for(let i=0;i<starCount;i++){const f=i/(starCount-1);arr[i*3]=(f-.5)*27+(Math.random()-.5)*.8;arr[i*3+1]=Math.sin(f*Math.PI*3)*1.5+(Math.random()-.5)*1.3;arr[i*3+2]=(Math.random()-.5)*4}}
targets.hero=new Float32Array(starCount*3);fillCosmos(targets.hero);targets.universe=new Float32Array(targets.hero);targets.instrumentation=new Float32Array(starCount*3);fillOptical(targets.instrumentation);targets.exoplanets=new Float32Array(starCount*3);fillOrbit(targets.exoplanets);targets.software=new Float32Array(starCount*3);fillLattice(targets.software);targets.trajectory=new Float32Array(starCount*3);fillTimeline(targets.trajectory);targets.contact=new Float32Array(targets.hero);starNow.set(targets.hero);
const cc=new THREE.Color();for(let i=0;i<starCount;i++){cc.setHex(Math.random()>.83?C.amber:C.ivory);const s=.25+Math.random()*.75;starColor[i*3]=cc.r*s;starColor[i*3+1]=cc.g*s;starColor[i*3+2]=cc.b*s}
const starGeom=new THREE.BufferGeometry();starGeom.setAttribute('position',new THREE.BufferAttribute(starNow,3));starGeom.setAttribute('color',new THREE.BufferAttribute(starColor,3));const stars=new THREE.Points(starGeom,new THREE.PointsMaterial({size:mobile?.052:.06,vertexColors:true,transparent:true,opacity:.84,sizeAttenuation:true,depthWrite:false}));scene.add(stars);let starTarget=targets.hero;

// ---------- Core + orbital geometry ----------
const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.08,4),new THREE.MeshBasicMaterial({color:C.amber,wireframe:true,transparent:true,opacity:.32}));root.add(core);const coreGlow=sprite(C.amber,6.4,.58);root.add(coreGlow);
function orbit(radius,rx,rz,color=C.amber,opacity=.1){const pts=new THREE.EllipseCurve(0,0,radius,radius,0,Math.PI*2).getPoints(180).map(p=>new THREE.Vector3(p.x,0,p.y));const line=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color,transparent:true,opacity}));line.rotation.x=rx;line.rotation.z=rz;orbitalRoot.add(line);return line}
[2,3,4.2,5.6,7.1].forEach((r,i)=>orbit(r,Math.PI/2+(i-2)*.055,(i-2)*.11,i===3?C.cyan:C.amber,.055+i*.018));orbit(5,.9,.38,C.rust,.11);orbit(6.4,1.08,-.6,C.cyan,.08);

// ---------- Featured research anchors ----------
const FEATURED=[
{id:'exohspec',label:'EXOhSPEC',type:'instrument',text:'Closed-loop thermal and adaptive-optics stabilisation for precision radial-velocity spectroscopy.',p:[-5.3,2.25,-.6],color:C.amber,url:'https://github.com/Biswajit1999'},
{id:'control',label:'Feedback Control',type:'instrument',text:'TEC response, AO correction, state-machine logic and environmental stability.',p:[-3.0,-1.8,1.2],color:C.amber,url:'https://github.com/Biswajit1999'},
{id:'project:wasp-121b-exoplanet-report',label:'WASP-121 b',type:'planet',text:'Ultra-hot Jupiter phase-curve analysis and extreme day/night thermal contrast.',p:[4.8,2.45,-1],color:C.cyan},
{id:'project:wasp-107b-exoplanet-report',label:'WASP-107 b',type:'planet',text:'Warm-Neptune atmospheric analysis with JWST-era archival observations.',p:[6,-.25,1.2],color:C.cyan},
{id:'project:hd189733b-exoplanet-report',label:'HD 189733 b',type:'planet',text:'Transmission-spectrum research on a hazy cobalt-blue hot Jupiter.',p:[3.5,-2.65,.15],color:C.cyan},
{id:'project:k2-18b-exoplanet-report',label:'K2-18 b',type:'planet',text:'Atmospheric evidence and interpretation for a temperate sub-Neptune.',p:[1.7,3.8,1.6],color:C.cyan},
{id:'detection',label:'Detection Methods',type:'software',text:'Transit, radial-velocity, microlensing and direct-imaging quantitative explainers.',p:[-1,4.75,-1.7],color:C.rust},
{id:'aether',label:'AETHER',type:'software',text:'Interactive particle, shader, mathematical and astrophysical visual experiments.',p:[1.2,-4.45,-1.2],color:C.rust},
{id:'software',label:'Research Software',type:'software',text:'Analysis pipelines, scientific web tools and feedback-control code.',p:[-5.1,-3.15,-1.4],color:C.rust},
{id:'papers',label:'Publications & Research',type:'research',text:'Papers, posters, technical writing and research documentation.',p:[5.4,-3.8,-2.5],color:C.green}
];
const featuredGroups=[],pickables=[],labels=[];const featuredById=new Map();
function labelFor(group,item){if(mobile)return;const el=document.createElement('span');el.className='node-label';el.textContent=item.label;labelLayer.appendChild(el);labels.push({el,obj:group,item})}
for(const item of FEATURED){const g=new THREE.Group();g.position.set(...item.p);g.userData=item;const halo=sprite(item.color,.9,.86);g.add(halo);const m=new THREE.Mesh(new THREE.SphereGeometry(.12,16,12),new THREE.MeshBasicMaterial({color:item.color}));m.userData=item;g.add(m);g.userData.pick=m;nodeRoot.add(g);featuredGroups.push(g);pickables.push(m);featuredById.set(item.id,g);labelFor(g,item)}
function connection(a,b,color,opacity=.08){const g=new THREE.BufferGeometry().setFromPoints([a,b]);const l=new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity}));nodeRoot.add(l);return l}
FEATURED.forEach((n,i)=>{connection(new THREE.Vector3(),new THREE.Vector3(...n.p),n.color,.075);if(i&&i%2===0)connection(new THREE.Vector3(...FEATURED[i-1].p),new THREE.Vector3(...n.p),n.color,.045)});

// ---------- EXOhSPEC optical bench ----------
instrumentRoot.visible=false;const benchMat=new THREE.LineBasicMaterial({color:C.amber,transparent:true,opacity:.34}),coldMat=new THREE.LineBasicMaterial({color:C.cyan,transparent:true,opacity:.32});
function frameBox(x,y,z,w,h,d,mat=benchMat){const f=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(w,h,d)),mat);f.position.set(x,y,z);instrumentRoot.add(f);return f}
frameBox(-9,-2.2,-4.2,1.7,1.1,1.1);frameBox(-5.7,-1.9,-3.4,1.25,1.5,.55,coldMat);frameBox(-2.3,-1.65,-2.7,1.7,.25,1.35);frameBox(1.4,-1.55,-1.8,1.8,.35,1.3);frameBox(5,-1.5,-.8,1.5,1.3,1.1,coldMat);frameBox(8.2,-1.45,.1,1.4,1.7,.4);
const grating=new THREE.Mesh(new THREE.BoxGeometry(1.5,.08,1.2),new THREE.MeshBasicMaterial({color:C.rust,transparent:true,opacity:.32}));grating.position.set(-2.3,-1.55,-2.7);grating.rotation.y=-.4;instrumentRoot.add(grating);
for(const p of [[-7.2,-.5,-3.7],[-4.2,-.3,-3],[-.5,-.2,-2.2],[3.2,-.35,-1.2],[6.8,-.3,-.25]]){const s=sprite(C.green,.48,.72);s.position.set(...p);instrumentRoot.add(s)}
const beamPts=[[-11,-2.2,-4.5],[-9,-2.2,-4.2],[-5.7,-1.9,-3.4],[-2.3,-1.65,-2.7],[1.4,-1.55,-1.8],[5,-1.5,-.8],[8.2,-1.45,.1],[11,-1.3,.8]].map(p=>new THREE.Vector3(...p));const beamCurve=new THREE.CatmullRomCurve3(beamPts);const beamLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints(beamCurve.getPoints(180)),new THREE.LineBasicMaterial({color:C.amber,transparent:true,opacity:.42}));instrumentRoot.add(beamLine);const beamPulse=sprite(C.ivory,.65,.9);instrumentRoot.add(beamPulse);

// ---------- Knowledge graph ----------
const GRAPH_URL='https://raw.githubusercontent.com/Biswajit1999/Biswajit_Jana.github.io/main/data/research-graph.json';let graphData=null,graphNodeMap=new Map(),graphVisuals=[],pulsePaths=[];
const FALLBACK_PROJECTS=[
{id:'project:55cancri-e-exoplanet-report',type:'Project',label:'55 Cancri e',slug:'55cancri-e-exoplanet-report',githubUrl:'https://github.com/Biswajit1999/55cancri-e-exoplanet-report',liveUrl:'https://biswajit1999.github.io/55cancri-e-exoplanet-report/'},
{id:'project:gj1214b-exoplanet-report',type:'Project',label:'GJ 1214 b',slug:'gj1214b-exoplanet-report',githubUrl:'https://github.com/Biswajit1999/gj1214b-exoplanet-report',liveUrl:'https://biswajit1999.github.io/gj1214b-exoplanet-report/'},
{id:'project:wasp-121b-exoplanet-report',type:'Project',label:'WASP-121 b',slug:'wasp-121b-exoplanet-report',githubUrl:'https://github.com/Biswajit1999/wasp-121b-exoplanet-report',liveUrl:'https://biswajit1999.github.io/wasp-121b-exoplanet-report/'},
{id:'project:wasp-107b-exoplanet-report',type:'Project',label:'WASP-107 b',slug:'wasp-107b-exoplanet-report',githubUrl:'https://github.com/Biswajit1999/wasp-107b-exoplanet-report',liveUrl:'https://biswajit1999.github.io/wasp-107b-exoplanet-report/'},
{id:'project:hd189733b-exoplanet-report',type:'Project',label:'HD 189733 b',slug:'hd189733b-exoplanet-report',githubUrl:'https://github.com/Biswajit1999/hd189733b-exoplanet-report',liveUrl:'https://biswajit1999.github.io/hd189733b-exoplanet-report/'},
{id:'project:k2-18b-exoplanet-report',type:'Project',label:'K2-18 b',slug:'k2-18b-exoplanet-report',githubUrl:'https://github.com/Biswajit1999/k2-18b-exoplanet-report',liveUrl:'https://biswajit1999.github.io/k2-18b-exoplanet-report/'}
];
function graphPosition(n,i,total){if(Number.isFinite(n.x)&&Number.isFinite(n.y)){const x=(n.x-800)/92,y=(550-n.y)/100,z=Math.sin(i*2.31)*5;return new THREE.Vector3(x,y,z)}const a=i/Math.max(total,1)*Math.PI*2,r=7+(i%5)*.6;return new THREE.Vector3(Math.cos(a)*r,Math.sin(a)*r*.66,(Math.random()-.5)*5)}
function graphColor(type){return type==='Instrument'?C.amber:type==='Method'?C.rust:type==='Molecule'?C.green:type==='PlanetClass'?C.cyan:type==='Project'?C.blue:C.dim}
function buildGraph(data){graphData=data;graphRoot.clear();graphVisuals=[];pulsePaths=[];graphNodeMap=new Map();const projects=(data.nodes||[]).filter(n=>n.type==='Project').slice(0,mobile?24:54);const related=(data.nodes||[]).filter(n=>['Instrument','Method','PlanetClass','Molecule'].includes(n.type)).slice(0,mobile?10:26);const chosen=[...projects,...related],ids=new Set(chosen.map(n=>n.id));chosen.forEach((n,i)=>{const p=graphPosition(n,i,chosen.length);const size=n.type==='Project'?.09:.055;const m=new THREE.Mesh(new THREE.SphereGeometry(size,10,8),new THREE.MeshBasicMaterial({color:graphColor(n.type),transparent:true,opacity:n.type==='Project'?.72:.44}));m.position.copy(p);m.userData={...n,text:n.label,type:n.type.toLowerCase()};graphRoot.add(m);graphVisuals.push(m);graphNodeMap.set(n.id,m);if(n.type==='Project')pickables.push(m)});(data.edges||[]).filter(e=>ids.has(e.source)&&ids.has(e.target)).slice(0,mobile?45:125).forEach((e,i)=>{const a=graphNodeMap.get(e.source),b=graphNodeMap.get(e.target);if(!a||!b)return;const curve=new THREE.QuadraticBezierCurve3(a.position.clone(),a.position.clone().add(b.position).multiplyScalar(.5).add(new THREE.Vector3(0,.25*Math.sin(i),.35*Math.cos(i))),b.position.clone());const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(20)),new THREE.LineBasicMaterial({color:C.dim,transparent:true,opacity:.08}));graphRoot.add(line);if(i%6===0){const p=sprite(graphColor(a.userData.type==='project'?'Project':a.userData.type),.24,.58);graphRoot.add(p);pulsePaths.push({obj:p,curve,phase:(i*.137)%1})}});graphRoot.visible=false;const projectCount=projects.length;if(graphStatus)graphStatus.textContent=`Graph · ${data.nodeCount||data.nodes?.length||projectCount} nodes`;}
try{const r=await fetch(GRAPH_URL,{cache:'force-cache'});if(!r.ok)throw new Error(r.status);buildGraph(await r.json())}catch(err){console.warn('Graph fallback',err);buildGraph({nodes:FALLBACK_PROJECTS,edges:[],nodeCount:FALLBACK_PROJECTS.length})}

// Merge graph metadata into featured anchors.
for(const f of FEATURED){const n=graphData?.nodes?.find?.(x=>x.id===f.id);if(n){Object.assign(f,{githubUrl:n.githubUrl,liveUrl:n.liveUrl,slug:n.slug});featuredById.get(f.id).userData=f;featuredById.get(f.id).userData.pick.userData=f}}

// ---------- Camera + scene state ----------
const SCENES={hero:{p:[0,2.4,19],t:[0,0,0],m:'hero'},universe:{p:[8.7,5.4,15.8],t:[0,.3,0],m:'universe'},instrumentation:{p:[-9,-2.8,11.2],t:[-.8,-1.55,-1.4],m:'instrumentation'},exoplanets:{p:[10.7,2.2,9.6],t:[3,.1,0],m:'exoplanets'},software:{p:[-10.7,4.2,13],t:[-1,-.4,0],m:'software'},trajectory:{p:[3,8.7,15.4],t:[0,0,0],m:'trajectory'},contact:{p:[0,.3,22],t:[0,0,0],m:'contact'}};
const sceneEls=qsa('[data-scene]'),railLinks=qsa('[data-rail]');let activeScene='hero',reduced=reduceMedia.matches,focused=null,hovered=null,mouseX=0,mouseY=0,dragging=false,dragLast={x:0,y:0},dragYaw=0,dragPitch=0;
const camPos=new THREE.Vector3(...SCENES.hero.p),camTarget=new THREE.Vector3(...SCENES.hero.t),desiredPos=camPos.clone(),desiredTarget=camTarget.clone(),restorePos=desiredPos.clone(),restoreTarget=desiredTarget.clone();
function applyScene(name,force=false){if(!SCENES[name]||(!force&&name===activeScene))return;activeScene=name;document.body.dataset.scene=name;starTarget=targets[SCENES[name].m]||targets.hero;instrumentRoot.visible=name==='instrumentation';graphRoot.visible=name==='universe'||name==='software';orbitalRoot.visible=name!=='software'&&name!=='trajectory';if(!focused){desiredPos.set(...SCENES[name].p);desiredTarget.set(...SCENES[name].t)}sceneEls.forEach(el=>el.classList.toggle('active',el.dataset.scene===name));railLinks.forEach(a=>a.classList.toggle('active',a.dataset.rail===name))}
function updateScroll(){let best='hero',bd=Infinity;const mid=innerHeight*.5;sceneEls.forEach(el=>{const r=el.getBoundingClientRect(),d=Math.abs(r.top+r.height*.5-mid);if(d<bd){bd=d;best=el.dataset.scene}});applyScene(best);const h=document.documentElement.scrollHeight-innerHeight;qs('#progress-bar').style.width=(h?scrollY/h*100:0)+'%';qs('#topbar').classList.toggle('scrolled',scrollY>20)}
addEventListener('scroll',updateScroll,{passive:true});updateScroll();

// ---------- Picking + focus ----------
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(10,10);
function panelData(d){qs('#node-kicker').textContent=(d.type||d.projectType||'Research node').replaceAll('-',' ');qs('#node-title').textContent=d.label||d.title||d.slug||d.id;qs('#node-text').textContent=d.text||d.headline||`Connected research node in the Biswajit Research Universe.`;const gh=qs('#node-link'),live=qs('#node-live');if(d.githubUrl||d.url){gh.href=d.githubUrl||d.url;gh.hidden=false}else gh.hidden=true;if(d.liveUrl){live.href=d.liveUrl;live.hidden=false}else live.hidden=true;qs('#node-panel').hidden=false}
function focusObject(obj){const wp=new THREE.Vector3();obj.getWorldPosition(wp);restorePos.copy(new THREE.Vector3(...SCENES[activeScene].p));restoreTarget.copy(new THREE.Vector3(...SCENES[activeScene].t));focused={obj,data:obj.userData};desiredTarget.copy(wp);const dir=new THREE.Vector3().subVectors(camera.position,wp).normalize();desiredPos.copy(wp).add(dir.multiplyScalar(5.2)).add(new THREE.Vector3(0,.8,0));panelData(obj.userData)}
function clearFocus(){focused=null;qs('#node-panel').hidden=true;desiredPos.set(...SCENES[activeScene].p);desiredTarget.set(...SCENES[activeScene].t)}
qs('#node-close').addEventListener('click',clearFocus);qsa('[data-focus]').forEach(b=>b.addEventListener('click',()=>{const g=featuredById.get(b.dataset.focus),m=g?.userData?.pick;if(m)focusObject(m);else{const gm=graphNodeMap.get(b.dataset.focus);if(gm)focusObject(gm)}}));
function updatePointer(e){pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;mouseX=e.clientX/innerWidth-.5;mouseY=e.clientY/innerHeight-.5}
canvas.addEventListener('pointermove',e=>{updatePointer(e);if(dragging){const dx=e.clientX-dragLast.x,dy=e.clientY-dragLast.y;dragYaw+=dx*.003;dragPitch=Math.max(-.35,Math.min(.35,dragPitch+dy*.002));dragLast={x:e.clientX,y:e.clientY}}});canvas.addEventListener('pointerdown',e=>{dragging=true;dragLast={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointerup',e=>{dragging=false;canvas.releasePointerCapture?.(e.pointerId)});canvas.addEventListener('click',e=>{if(Math.abs(e.clientX-dragLast.x)>6||Math.abs(e.clientY-dragLast.y)>6)return;updatePointer(e);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(pickables,false);if(hits[0])focusObject(hits[0].object)});

// ---------- Labels + motion ----------
function updateLabels(){if(mobile)return;const w=innerWidth,h=innerHeight;labels.forEach(({el,obj,item})=>{const p=new THREE.Vector3();obj.getWorldPosition(p);p.project(camera);const visible=p.z<1&&p.z>-1&&Math.abs(p.x)<1.12&&Math.abs(p.y)<1.12;el.style.opacity=visible?(hovered?.userData?.id===item.id||focused?.data?.id===item.id?1:.62):0;el.style.left=(p.x*.5+.5)*w+'px';el.style.top=(-p.y*.5+.5)*h+'px';el.classList.toggle('hot',hovered?.userData?.id===item.id||focused?.data?.id===item.id)})}
const motionBtn=qs('#motion-toggle');function applyMotion(){document.body.classList.toggle('reduced-motion',reduced);motionBtn.setAttribute('aria-pressed',String(reduced));motionBtn.textContent=reduced?'Motion off':'Motion'}motionBtn.addEventListener('click',()=>{reduced=!reduced;applyMotion()});applyMotion();
function resize(){renderer.setSize(innerWidth,innerHeight,false);renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<820?1.3:1.75));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize,{passive:true});

// ---------- Render loop ----------
const clock=new THREE.Clock();function animate(){const t=clock.getElapsedTime(),attr=starGeom.attributes.position,morphEase=reduced?.1:.028;for(let i=0;i<starNow.length;i++)starNow[i]+=(starTarget[i]-starNow[i])*morphEase;attr.needsUpdate=true;const ce=reduced?.16:.045;camPos.lerp(desiredPos,ce);camTarget.lerp(desiredTarget,ce);camera.position.copy(camPos);if(!reduced&&!focused){camera.position.x+=mouseX*.34;camera.position.y-=mouseY*.2}camera.lookAt(camTarget);if(!reduced){root.rotation.y=Math.sin(t*.1)*.035+dragYaw;root.rotation.x=dragPitch;orbitalRoot.rotation.y=t*.017;core.rotation.x=t*.075;core.rotation.y=t*.12;stars.rotation.y=t*.0022}featuredGroups.forEach((g,i)=>{const isF=focused?.data?.id===g.userData.id,isH=hovered?.userData?.id===g.userData.id,s=isF?2:isH?1.45:1;g.scale.lerp(new THREE.Vector3(s,s,s),.09);if(!reduced)g.position.y=FEATURED[i].p[1]+Math.sin(t*.55+i)*.075});coreGlow.material.opacity=.52+Math.sin(t*1.35)*.07;pulsePaths.forEach(p=>{const f=(t*.075+p.phase)%1;p.obj.position.copy(p.curve.getPoint(f));p.obj.material.opacity=.16+Math.sin(f*Math.PI)*.55});if(instrumentRoot.visible)beamPulse.position.copy(beamCurve.getPoint((t*.12)%1));if(!reduced){raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(pickables,false)[0];hovered=hit?.object||null;canvas.style.cursor=hit?'pointer':dragging?'grabbing':'grab'}updateLabels();renderer.render(scene,camera);requestAnimationFrame(animate)}
applyScene('hero',true);animate();setTimeout(()=>boot?.classList.add('done'),350);
})();
